services:
  db:
    image: postgres:16-alpine
    container_name: tekado-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tekado_user
      POSTGRES_PASSWORD: tekado_pass
      POSTGRES_DB: tekado_db
    ports:
      - "5432:5432"
    volumes:
      - tekado_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tekado_user -d tekado_db -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  tekado_pgdata:
