apiVersion: v1
kind: Service
metadata:
  name: tekado-backend
  namespace: tekado
spec:
  type: NodePort
  selector:
    app: tekado-backend
  ports:
    - name: http
      port: 8000        # service port inside cluster
      targetPort: 8000  # container port
      nodePort: 30080   # external port on the node (must be between 30000-32767)

