apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: tekado
type: Opaque
stringData:
  POSTGRES_USER: tekado_user
  POSTGRES_PASSWORD: tekado_pass
  DATABASE_URL: postgresql://tekado_user:tekado_pass@tekado-postgres:5432/tekado_db?schema=public

