apiVersion: v1
kind: Service
metadata:
  name: tekado-postgres
  namespace: tekado
  labels:
    app: tekado-postgres
spec:
  clusterIP: None   # <-- headless service (Option A requirement)
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: tekado-postgres
